### ISSUE TITLE
Timeline for Script Handling

### ISSUE THREAD

**Issue by Xansul** [MycroftAI/skill-homeassistant#101]
Hello, do we have a timeline for adding the ability to call Home Assistant scripts? I'd love to help out in any way to get this ability added.

**Comment by Tony763** [comment]
Hi @Xansul, scripts should be accessible with automation intent. Try to use master branch in this repository as all changes are still not released to marketplace.

**Comment by Xansul** [comment]
Thanks for the reply. I just cloned the master branch into my Mycroft setup, however I can't seem to get it to understand the command to call scripts. Is there a specific command that is used?

**Comment by Tony763** [comment]
Hi @Xansul, sorry for late reply. `(Activate|Fire|Call up|Trigger|Set) (the|) (automation|scene|script) {Entity}.` is used in English for activating automations so `Activate script {Entity}` should do a job.

**Comment by Tony763** [comment]
Hi @Xansul, let me know if this is still a problem for You, please. I did not find anything wrong.

**Comment by Xansul** [comment]
Hi @Tony763,

Thanks for the response, that's what I was looking for. I'll close the issue.
