### ISSUE TITLE
Check device status before/after issuing commands

### ISSUE THREAD

**Issue by ChristopherRogers1991** [MycroftAI/skill-homeassistant#11]
As flagged in https://community.mycroft.ai/t/homeassistant-skill-misinterprets-request/6453/39, there is currently no error if you try to control a device that is offline.

This is in part due to limitations of the home assistant API, which issues an HTTP 200 (successful) response regardless of whether it was able to actual take the action issued. To resolve this, I think we'd need to query the device before (and potentially after) issuing commands, to confirm they are online, and then that the command actually worked. This would introduce some obvious race conditions, but I think in practical terms, people are unlikely to hit those.

**Comment by stratus-ss** [comment]
i'm closing this as very stale. We aren't going to switch to the common iot framework anytime soon
