### ISSUE TITLE
Connection to home assistant fails with unclear error message if access token not configured

### ISSUE THREAD

**Issue by generalsmithers** [MycroftAI/skill-homeassistant#13]
If a long-lived access token for homeassistant is not configured and the user attempts to use the homeassistant skill, the response from mycroft does not mention that a token is required.

**Comment by damanbaird** [comment]
i used a long-lived access token and still cant get it to connect

**Comment by koalatron-9000** [comment]
I am also having the same error. I have a long-lived access token that I cut & pasted into the configuration. But when I ask mycroft to do anything through my home assistant, I get the bellow error:
fresh install of home assistant (rpi2) and mycroft(rpi3)
![home assistant error](https://user-images.githubusercontent.com/19487364/80542081-3effb580-8961-11ea-8ae0-1edd0827883e.PNG)

**Comment by Tony763** [comment]
hi @koalatron-9000, try this [branch](https://github.com/Tony763/mycroft-homeassistant/tree/turn_on_all-group) and let me know.

Added:
- check if IP and Token is present in config and inform if missing.
- inform if Token was not accepted

**Comment by koalatron-9000** [comment]
Now mycroft responds with an error about "no running timers"
![mycroft screenshot](https://user-images.githubusercontent.com/19487364/80639372-c52a0380-8a16-11ea-8717-45eb6c7d600a.png)

**Comment by Tony763** [comment]
if you write :skills is HA skill listed?

**Comment by koalatron-9000** [comment]
no. it is no longer listed when I type skills, nor is it listed on the website under my skills section. But it is still in opt/mycroft/skills with everything else

**Comment by Tony763** [comment]
Try:
```
cd /opt/mycroft/skills/
rm -R mycroft-homeassista*	
git clone -b turn_on_all-group https://github.com/Tony763/mycroft-homeassistant.git mycroft-homeassistant.mycroftai
```

Or:

mycroft-msm install https://github.com/Tony763/mycroft-homeassistant.git

**Comment by Tony763** [comment]
Hi @generalsmithers, could you test latest master branch? PR fixing this issue is merged so if its ok, could you close the issue, please?

**Comment by Tony763** [comment]
Hi @krisgesling, close this please, fix was merged.
