### ISSUE TITLE
Can't turn off all lights

### ISSUE THREAD

**Issue by TheLastProject** [MycroftAI/skill-homeassistant#20]
https://github.com/MycroftAI/mycroft-homeassistant/blob/19.02/regex/en-us/switch.rx#L2 makes me think the phrase `turn off all lights` should work. However:

```
 turn off all lights                
 >> Entity "all" could not be found.
 turn off lights                    
 >> turned off all lights.          
```

**Comment by andlo** [comment]
I can confirm - this also happens at my place.

**Comment by fermulator** [comment]
same here;
TIP: I suspect a "workaround" would be to create and name a light group called "all"? ;/

**Comment by Tony763** [comment]
This correspond with #37.  If #25 will be merged, I can try to rewrite also this.

**Comment by Tony763** [comment]
@TheLastProject @andlo  - try this [branch](https://github.com/Tony763/mycroft-homeassistant/tree/turn_on_all-group). It works for on/off by domains (light, switch)

**Comment by fermulator** [comment]
with #54 in, does it mean i should retest? :)

**Comment by Tony763** [comment]
@fermulator Yes, if you could. If it works, we could close this.

**Comment by fermulator** [comment]
sorry - to clarify, should i test off your branch? or has it already been delivered to the main branch?

**Comment by Tony763** [comment]
Main, as it's already merged to MycroftAI:20.08.

**Comment by Tony763** [comment]
Hi @fermulator  did you have time to test it?
Hi @TheLastProject, as PR is merged, could you also test it, please? If it's ok, could You close the issue?

**Comment by TheLastProject** [comment]
Sorry, but I do not currently have a working Mycroft install anywhere and thus I cannot test this

**Comment by stratus-ss** [comment]
I'm closing this issue as the reporter has decided to move on for now
