### ISSUE TITLE
fallback to HA conversation is never used

### ISSUE THREAD

**Issue by andlo** [MycroftAI/skill-homeassistant#23]
It seems like the fallback to Homeassistant conversation is never used.

it seems that nomatter if ```“enable_fallback”: true ``` the skill still thinks it is false.

In lines 59..61 is the problem.

``` python
                if conversation_activated:
                    self.enable_fallback = \
                        self.settings.get('enable_fallback') == 'true'
 ```
should be 
``` python
                if conversation_activated:
                    self.enable_fallback = \
                        self.settings.get('enable_fallback')
 ```
Then it works.

I made a fix in the fix_fallback branch and will PR that to the default if/when someone confirms it is working for them too.

**Comment by sup08228** [comment]
I confirm that this has fixed the issue.  It is correctly falling back.  Thanks andlo!!

**Comment by andlo** [comment]
@krisgesling mentioned that due to changes in settingsmeta.json we should waite a bit until merging....
