### ISSUE TITLE
Covers

### ISSUE THREAD

**Issue by adas4190** [MycroftAI/skill-homeassistant#24]
I cannot controll covers with it? Is it something I do wrong? Thank You

**Comment by andlo** [comment]
Hi @adas4190 
As far as I can red the code for now the homeassistant skill only handles thies domains

           entity,
            [
                'group',
                'light',
                'fan',
                'switch',
                'scene',
                'input_boolean',
                'climate'
            ]

But you can use the fallback feature and make things happen by an intent script. 

Or you can make a template switch that controls yuor cover.
