### ISSUE TITLE
Failed to upload settingsmeta

### ISSUE THREAD

**Issue by gabipintea** [MycroftAI/skill-homeassistant#27]
Hi! First of all, very good job with this skill. Keep up the good work!
I recently updated to mycroft-core 20.2.0 and after failing to update, i just clean installed picroft again.

Running on Raspberry Pi 3, after installing Home Assistant skill i get the following in mycroft-cli
```
`~~~~ | WARNING  |   640 | mycroft.skills.settings:_update_settings_meta:306 | DEPRECATION WARNING: The "name" attribute in the settingsmeta file is no longer supported.
 20:13:41.746 | ERROR    |   640 | mycroft.skills.settings:_issue_api_call:315 | Failed to upload skill settings meta for homeassistant|20.02
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 312, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 382, in upload_skill_metadata
    "json": settings_meta
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 69, in request
    return self.send(params)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 152, in send
    return self.get_response(response, no_refresh)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 174, in get_response
    raise HTTPError(data, response=response)
~~~~ ["Couldn't interpret 'False' as string."]}, '1': {'value': ["Couldn't interpret 'True' as string."]}, '2': {'value': ["Couldn't interpret 'True' as string."]}}}}`
```
Any idea?

**Comment by sup08228** [comment]
I second the comment above, awesome skill!  I am also getting the same error.

**Comment by andlo** [comment]
You could try changing to the 20.02 branch by 
```
git checkout 20.02
```
in the skill directory /opt/mycroft/skills/homeassistant.mycroftai

This branch seems to work on the 20.02 release of mycroft-core. Dont yet know why this brans isnt set as defautl.

**Comment by forslund** [comment]
@krisgesling did the modification on friday correcting the settingsmeta.yml, we're still discussing if it should really be left as is and the backend should be changed to accept the `false`value. so we'll see where we land tomorrow.

20.02 branch should work for now but if it's changes back there may be an issue with settings disappearing from home.

**Comment by gabipintea** [comment]
I did the 'git checkout 20.02' and now everything is working just fine. Thank you very much!
