### ISSUE TITLE
Vacuum integration.

### ISSUE THREAD

**Issue by Lex-talionis** [MycroftAI/skill-homeassistant#32]
I installed this and i'm happy its working as expected. I want to use it with my vacuum integration that  i got from here https://github.com/BnMcG/PyRobovac. It works manually through the home assistant dashboard but not through mycroft voice command. Its response is "Sorry cant find the Home Assistant entity "vacuum manuel". 

The entity is named this "vacuum.manuel" on my home assistant which I can see in developer-tools/state on home assistant, I can also see the state is currently set to "off" when "off" and on when on.

My questions are:

Am i right in thinking because it uses fuzzy words that it should at least understand that that entity exists?

Should this work out the box or will i need to do some more work to get ti to work?

Thanks in advance.

**Comment by andlo** [comment]
Hi I dont think the homeassistant-skill regonize entities from vacum domain. Så you have to work around that. I see three ways to go:

1: Activate the falback intent in the homeassistant skill on the skill-settings page. Add a intent to activate your vacum.

2: Add a template switch and have that activate you vacum 

3: Add support for vacum domain to homeassistant skills 

I think 1 or 2 is the easiest way for now.

**Comment by Lex-talionis** [comment]
Thanks for the quick response.

After looking at the source I see theres a list of domains that contain group, lights etc. I assume this is what you mean in your 3rd point. I'm new to homeassistant and mycroft so I'll have to figure out how to do 1 or 2.

Really appreciate your help. 

I am a dev by trade but I dont use python

**Comment by andlo** [comment]
Yes that is what I ment.

I am not a dev but know python ;)

**Comment by andlo** [comment]
Ill close this issue as I think it is beeing answered. Fell free to reopen or open a new one.
