### ISSUE TITLE
process for new vocab - scene via "Hey Mycroft, it's <scene name>"

### ISSUE THREAD

**Issue by fermulator** [MycroftAI/skill-homeassistant#34]
Hello! This issue is more of a question to start, but based on answers I'd like to submit a PR.

As per https://github.com/MycroftAI/mycroft-homeassistant/blob/20.02/vocab/en-us/AutomationActionKeyword.voc, we have some initial great vocab for activating scenes/automation in home assistant.

We have some scenes like:
* "Movie Time"
* "Bed Time"
* "Entertaining Main Floor"

So we can activate them with:
* "Hey Mycroft, activate <scene name>"
* "Hey Mycroft, activate scene <scene name>"
* "Hey Mycroft, trigger <scene name>"
(same for <automation script name>)

So! To make it slightly more intuitive, we are thinking it would be +1 cool factor to just say:
* "Hey Mycroft, it's <scene name>" --> ex "Hey Mycroft, it's Movie Time"

So, questions:
1. is there a process for this project to extend vocab?
2. are there potential for conflicts with generic mycroft vocab? (i.e. in this case "it's" is arguably a generic word...)

thx!

**Comment by Tony763** [comment]
1. Simple PR.
2. _HA skill use higher priority for fall back. So it should test intens as first, if it not find wanted scene, it will fallback to another skill._ EDIT: Will not fallback, but say it did not find entity. 
``` 
        # Needs higher priority than general fallback skills   
        self.register_fallback(self.handle_fallback, 2)
```
I would try use it as "Hey Mycroft, it's 'scene', now." --> ex "Hey Mycroft, it's Movie Time, now"

With scene named `Movie`:
![image](https://user-images.githubusercontent.com/5598750/80150387-9811c700-85b8-11ea-9ae8-638d0b9ed1e6.png)
HA needs at least 50 % match - it mabye should be higher.
``` 
    # require a score above 50%   
      best_score = 50
``` 
![image](https://user-images.githubusercontent.com/5598750/80150462-be376700-85b8-11ea-835b-c0266e455ab2.png)
![image](https://user-images.githubusercontent.com/5598750/80150505-d0b1a080-85b8-11ea-86bf-105dba0ab28f.png)

**Comment by stratus-ss** [comment]
i'm closing this because it appears to be stale. Please reopen if it is still an issue
