### ISSUE TITLE
Mycroft cannot install

### ISSUE THREAD

**Issue by czadikem** [MycroftAI/skill-homeassistant#42]
Mycroft says "an error occured while installing the dependancies for home assistant"  when I try to install this skill

**Comment by gador** [comment]
Hi @czadikem ,

we need more information. What enclosure do you have (Picroft or mark I)?
Also, do you have access to the command line and can share the logs?

**Comment by Tony763** [comment]
Hi, also which version of python you are using?

**Comment by Tony763** [comment]
Hi  @czadikem, is this still issue for you? If not, could you close the issue, please?

**Comment by stratus-ss** [comment]
closing this as the original user has not replied to the issue in some time
