### ISSUE TITLE
Setting Alarms

### ISSUE THREAD

**Issue by inquanto** [MycroftAI/skill-homeassistant#43]
Hi there,

Thanks a lot for the amazing skill. I was wondering if there is any way to have data flowing from mycroft into home assistant as an event or something,  So that for example an alarm set in mycroft could then be automated in homeassistant.

**Comment by Tony763** [comment]
Hi, to understood for example: when mycroft alarm is activated, you want to run automation in HA ( turn on light, set temperature, open curtains, etc..)

This would be mabye posible if ther is way to check if exac skill is loaded from other skill. If yes, then it would only mean to add check if home assistant is loaded to alarm skill and with each activation triger set automation action with name of alarm and in HA create automation with that name.

**Comment by stratus-ss** [comment]
closing this ticket as being stale. 

I would think this would require a new skill in order to coordinate between the Alarm Skill and the Home Assistant skill
