### ISSUE TITLE
The image links in the readme are broken

### ISSUE THREAD

**Issue by TheLogan** [MycroftAI/skill-homeassistant#44]
As the title says, the image links are broken and simply redirect to a github 404 page.
This happens on the 20.8 and the 20.2 branches, but they still work for the 19.02 branch and some of the other branches too

**Comment by Tony763** [comment]
Hi, these files were removed in some commit as they were stored in root with no good names. I am waiting for approve of my PR #38. Hope it will be reviewed in next 4 weeks. After that I will dig into this. ( I do not want to make next merge conflict)

**Comment by stratus-ss** [comment]
Thanks for the fix @Tony763 you've been putting in a lot of work that has spurred us on to action @krisgesling and I have started cleaning up the code in the commonIoT branch and we are slowly working towards shifting to this as the core. 

In the mean time you have been doing a great job addressing some of the issues in the 20.x branches thanks a lot!

**Comment by Tony763** [comment]
@stratus-ss   Hopefully You will merge all my PRs as I do not plan to use commonIoT. For me everything that do something with home automation is and will be controlled trough Home Assistant so for me there is no use for commonIoT.

At last lot of these issues you will actually face even in commonIoT.

**Comment by krisgesling** [comment]
Yeah, I can imagine that a lot of HA users may not see the need right now. It will become more important over time. Either way we definitely want to incorporate all your updates. As you said there are some common problems between the two and would be great to include the new features you are adding.
