### ISSUE TITLE
Can’t get this working..

### ISSUE THREAD

**Issue by ghost** [MycroftAI/skill-homeassistant#47]
On latest picroft version, valid long term token but keep getting this error trying to run anything on home assistant.

![8303346E-06C4-4E6A-9223-D2A41371CAF6](https://user-images.githubusercontent.com/61924853/93910383-416efd00-fcbe-11ea-9444-755b65847f5b.png)

**Comment by Tony763** [comment]
Hello, try this branch [Tony763:turn_on_all](https://github.com/Tony763/mycroft-homeassistant/tree/turn_on_all-group-squash). I added few checks, so Mycroft should inform You if anything from settings is missing. Also lot of code was re-wrote.

**Comment by ghost** [comment]
> Hello, try this branch [Tony763:turn_on_all]

Ok I tried that branch and still get the same issue, don’t see any other errors.

![340E4E58-3AFF-4E5B-B281-6E5A4FDA1C9A](https://user-images.githubusercontent.com/61924853/93912060-79773f80-fcc0-11ea-9be8-d4b931d222af.png)

**Comment by ghost** [comment]
Also I am trying to activate a scene if that makes a difference.. I tried “trigger Plex” before which didn’t work now so I tried “turn on Plex” this time which still isn’t working.

**Comment by Tony763** [comment]
Ouch, my bad. Pull it once again, local variable error fixed.

**Comment by ghost** [comment]
> Ouch, my bad. Pull it once again, local variable error fixed.

Ok I ran msm update and it did update the skill. This is the new error message I’m getting.
![36523E84-866C-41D0-B331-4B8C63D6292F](https://user-images.githubusercontent.com/61924853/93919094-7da85a80-fcca-11ea-8c9e-033ebc18c7ea.png)

**Comment by Tony763** [comment]
Did you try anything other than plex?
As plex You mean [plex](https://www.home-assistant.io/integrations/plex/#media-player) media server?

**Comment by ghost** [comment]
> Did you try anything other than plex?
> As plex You mean [plex](https://www.home-assistant.io/integrations/plex/#media-player) media server?

Yeah it’s a scene to hit play on my Plex player and I tried created a new scene just changing my light color and that did work. I tried manually running the Plex scene on HA itself and it gave me an error.. so I’m guessing my issue was with the Plex Intergration on HA itself not picroft..

**Comment by Tony763** [comment]
@tempuser0012  Ok, let me know, what caused it. If it was as error response hrom HA, component should properly inform about it, not just crash.
