### ISSUE TITLE
Cant controll Area

### ISSUE THREAD

**Issue by Y0ngg4n** [MycroftAI/skill-homeassistant#76]
**Describe the bug**
I cant say `turn on [Area]`. It always just enables the first entity in the Area.

**Comment by Tony763** [comment]
Hi @Y0ngg4n, areas are quite new and I think, they are not implemented in this skill, yet. I will look into it.

**Comment by stratus-ss** [comment]
Areas are not implemented in the skill

**Comment by Tony763** [comment]
Also all I have found so far, is that areas cannot be used in this way. They are just to sort devices by their physical placement. For controlling them, you should use groups. [HA forum](https://community.home-assistant.io/t/how-do-you-use-areas/261889) I also checked development tools in HA and there is no entry with areas in entities but I have one set.

**Comment by Y0ngg4n** [comment]
@Tony763 thank you for the info to use groups

**Comment by Tony763** [comment]
@Y0ngg4n Could You close the issue, please?
