### ISSUE TITLE
Normalize IP address setting

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/skill-homeassistant#79]
**Is your feature request related to a problem? Please describe.**
An issue I've seen reported many times over the years is that people enter their host / ip address settings in different ways and it's not clear which format should be used. For example you might enter:
- `192.168.1.100`
- `http://192.168.1.100`
- `http://192.168.1.100/`
- `https://192.168.1.100`
- perhaps others?

**Describe the solution you'd like**
Ideally we would accept any logical format and normalize these to what the Home Assistant client expects.

**Describe alternatives you've considered**
Alternatively we can improve the documentation about what is required, but as much as I love documentation, I also know that most people don't read it.

**Comment by Tony763** [comment]
Ok, will check.

**Comment by krisgesling** [comment]
Not an essential thing, just something I've noticed and thought it might make a good Hacktoberfest project for someone - but feel free to take it on yourself too :)

**Comment by Tony763** [comment]
'ha_client.py' expect pure IP or domain name so it should by doable with some small regex.

BTW: It's 7. and I still do not have my 4 accepted commits :)

**Comment by krisgesling** [comment]
ooh they're increasing the requirements this year!

It's so wildly different - you get lots of people trying to submit single letter typo fixes, and others writing an entire Skill for a single PR.

**Comment by pfefferle** [comment]
Can this be closed?

**Comment by Tony763** [comment]
Hi @krisgesling, could You close this as it's merged.
