### ISSUE TITLE
Misinterpreting numbers in utterance

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/skill-homeassistant#8]
[Issue from Forums](https://community.mycroft.ai/t/homeassistant-skill-misinterprets-request/6453), text copied here:

> I have a working Homeassistant and have installed the Homeassistant skill on Mycroft. Mycroft appears to communicate with my HA instance. I can manipulate one of my actuators with verbal or typed commands.
> 
> I have some other actuators ( reflashed Sonoff with Tasmota ). Since I have four of these, their name on HA are suffixed with the numbers 1-4. The skill seems to get fixated on one particular actuator and ignores the number I actually want to address. This is not a speech recognition problem since a typed command does not work either.
> 
> In short “turn on blabla 1” will result in mycroft trying for instance to manipulate “blabla 3”.

**Comment by scottsweb** [comment]
I am seeing a similar issue to this. Any device with at least some shared name is being confused for another. 

> Hey Mycroft, turn on the lounge lights

becomes

> Lounge lamp turned on

...

> Hey Mycroft, turn on the TV

becomes:

> TV Mute was turned on

I have just upgraded from Mycroft 18 with the old pre-forked skill. Everything was working as expected on the older stack.

**Comment by stratus-ss** [comment]
@scottsweb is this still valid on your setup? I haven't seen this in my testing but I don't have many of these use cases

**Comment by scottsweb** [comment]
@stratus-ss I turned off my Mycroft Pi a few months ago as I wasn't really using it much. It was still getting confused until that point in time.

**Comment by stratus-ss** [comment]
Closing this issue as stale
